#include <stdlib.h> // Standard library functions (e.g., malloc, free, exit)
#include <stdio.h> // Input/output functions (e.g., printf, scanf)
#include <stdbool.h> // Boolean data type (true, false)
#include <unistd.h> // POSIX operating system API (e.g., fork, sleep, getpid)
#include <signal.h> // Signal handling functions

int main(){
  // Create a signal set to hold signals to be blocked
  sigset_t blocks; 
  // Initialize the signal set to be empty
  sigemptyset(&blocks);
  // Add the SIGINT signal (generated by Ctrl+C) to the signal set
  sigaddset(&blocks,SIGINT);
  // Block the signal set in the current process
  // SIG_BLOCK: Add the signal set to the blocked signals
  // &blocks: The signal set to be blocked
  // &prevs: A pointer to a signal set that will be filled with the previous blocked signals
  sigprocmask(SIG_BLOCK,&blocks,&prevs);
  
  // Infinite loop
  while(true){
    // Print the process ID (PID) of the current process
    printf("I bet you can't KILL me, mr. %u\n",getpid());
    // Pause execution for 1 second
    sleep(1);
  }
  
  return 0; // Unreachable code, the program never exits the loop
}
