* Agenda
- Miscelania
  - Whether char is signed or unsigned is a /compiler/ level decision
  - Yes, dereferencing a freed pointer is *technically* undefined but
    - for small (malloced) regions will be random garbage inside owned memory
    - for a big enough region you *might* be able to force a segfault if it affects the virtual memory allocation
- first.last@cslinux.pcc.edu      
- Review of bit-twiddling operations
  - Another couple of hand operations to make it clear
    (3 << 2) ^ 5

    (11 << 2) ^ (101)
    (1100) ^ (0101)
    = 1001 
  - xor and one-time pad
    (a ^ b) ^ a = b
    Proof:
    Assumptions:
    \forall a b. a ^ b = b ^ a (commutativity)
    \forall a b c. (a ^ b) ^ c = a ^ (b ^ c) (associativity)
    \forall a. a ^ a = 0 (involutivity)
    \forall a. 0 ^ a = a
    With these three properties we can perform the following
    equational transformations
    (a ^ b) ^ a = a ^ (a ^ b) (by comm)
    a ^ (a ^ b) = (a ^ a) ^ b (by assoc)
    (a ^ a) ^ b = 0 ^ b (inv)
    (0 ^ b) = b (identity)
    
  - Flags qua bit-twiddling
- 2's complement math, by hand
  
  Reminder:
  (8-bit)
  Standard way of decoding a bit-string into an unsigned int:
  b7 b6 b5 b4 b3 b2 b1 b0 (\forall b_i b_i = 0 \/ b_i = 1)

  = \Sum_{i=0}^7 b_i*2^i
  00110111
  = 0 * 2^7 + 0 * 2^6 + 1 * 2^5 + 1 * 2^4 + 0*2^3 + 1*2^2 + 1*2^1 + 1*2^0 = 64 + 32 + 16 + 4 + 2 + 1 = 119

  *signed*
  = -b7^2^7 + \Sum_{i=0}^6 b_i*2^i

  if all 1s then this becomes -2^7 + (\Sum_{i=0}^6 2^i)
  we know though what 1 + 2 + 4 + ... + 2^j is = 2^{j+1} - 1

  -2^7 + (2^7 - 1) = -1

- How does casting the sizes of integers play with 2s complement?
  - going from smaller to larger
  - going from larger to smaller
- Overflow
  - for convenience `#include <limits.h>`, `INT_MAX`, `INT_MIN`
  - from addition
  - from *multiplication*
    - How many bits are needed to store the multiplication of an m bit and n bit number?
    0 --> (2^m)-1, vs 0 --> (2^n)-1
    ~~ (2^m)*(2^n) = 2^(m+n)
     
- Starting floating point
  - Why is it called floating point?
    floating point as opposed to "fixed point"
    fixed point meaning there is a set number of places to
    the left and right of the decimal

    0000.00 <-- fixed point
    log_2(100000) = log_2(10^5) = 5 * log_2(10) 
    
    floating point is
    0.1234
    4.1
    0.00000000000000000001
  - Look at an approximation issue in floating point
  - Is this a design flaw?
  - Cardinality
    - Cardinality is the size of a mathematical set
    - Every set, even an infinite set, has a "size"
    - The integers have an infinite size of aleph_0
    - The real numbers have size continuum (c)
      - The weird property: there are as many real numbers in (0,1) as there are in the entire real number line
      - This is a much bigger infinity than aleph_0
      - In fact it has the size of aleph_0^{aleph_0}
  - Changing our bit munger to deal with floats
